# Package Overview
package_name: classification_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
target: survived

pipeline_name: classification_model
pipeline_save_file: classification_model_output_v

features:
  - age
  - fare
  - sex
  - cabin
  - embarked
  - title

# size of test set
test_size: 0.1

# random seed for reproducibility
random_state: 0

# model hyperparameter
param_c: 0.0005

numerical_variables:
  - age
  - fare

categorical_variables:
  - sex
  - cabin
  - embarked
  - title

cabin: cabin